var fruits;
fruits = ['Mango', 'Grapes', "fruits"];
console.log(fruits);
var animal;
animal = ['Lion', 'Fox', "Rabbit"];
console.log(animal);
var person;
person = ['Mohan', 40, 'prem', 25, 'latha', 40,];
console.log(person);
var persons;
persons = ['Mohan', 40, 'prem', 25, 'latha', 40, true, 55.14];
console.log(persons);
